name: CI workfow

on:
  push:
    branches: 
      - laura/*
      - celine/*
      - christoffer/*
      - master
  pull_request:
    branches:
      - laura/*
      - celine/*
      - christoffer/*
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 22
      uses: actions/setup-java@v4
      with:
        java-version: '22'
        distribution: 'temurin'
        cache: maven
    - name: Build without tests 
      run: mvn -B package -DskipTests=true
  
    - name: Upload Surefire Reports
      if: always()  # Sørg for, at rapporterne uploades, selvom testen fejler
      uses: actions/upload-artifact@v3
      with:
        name: Surefire-Reports
        path: target/surefire-reports
